### ISSUE TITLE
anyone has any problems after recent upadtes? arch

### ISSUE THREAD

**Issue by Seme4eg** [Frewacom/pywalfox#123]
Updated packages on arch just like 3 days ago and now getting 'Fetch failed: You are not connected to the Pywalfox daemon'. 
`pywalfox -v` shows v2.7.4
`pywalfox update` - no errors
`pywalfox start` - no errors
`pywalfox log` throws error:

```
❯ pywalfox log
Traceback (most recent call last):
  File "/usr/bin/pywalfox", line 33, in <module>
    sys.exit(load_entry_point('pywalfox==2.7.4', 'console_scripts', 'pywalfox')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pywalfox/__main__.py", line 148, in main
    handle_args(args)
  File "/usr/lib/python3.12/site-packages/pywalfox/__main__.py", line 129, in handle_args
    open_log_file()
  File "/usr/lib/python3.12/site-packages/pywalfox/__main__.py", line 88, in open_log_file
    subprocess.call([editor, LOG_FILE_PATH])
  File "/usr/lib/python3.12/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'emacsclient -c'
```

**Comment by th3cr00k3dm4n** [comment]
yes getting this error after update

**Comment by Seme4eg** [comment]
@th3cr00k3dm4n , you mean uninstalling AUR package? or how do you have it installed. Or uninstalling via `pywalfox uninstall`? Cuz for me neither of those 2 worked. Unless  you have this package installed from different source rather than AUR.
