### ISSUE TITLE
`importlib.metadata.PackageNotFoundError` Error on any interaction with pywalfox binary

### ISSUE THREAD

**Issue by TrimVis** [Frewacom/pywalfox#124]
Hi, first of all I installed pywalfox through the AUR using `paru -S python-pywalfox`.
Initially it worked great, but after a system upgrade I am now receiving the following error (on any interaction with the pywalfox binary):

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pywalfox", line 33, in <module>
    sys.exit(load_entry_point('pywalfox==2.7.4', 'console_scripts', 'pywalfox')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/pywalfox", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 862, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pywalfox
```

This seems like a packaging issue (as its complaining about missing package metadata), but I never really worked with python packaging, so this is just a wild guess. I'm running Python 3.12.3 (I think this changed during the update)

I tried reinstalling the package, but the issue still persists.
It seems that you are also the maintainer of the AUR package, so I hope this is the right location to report this issue.

In case you need any other specs about my environment feel free to tell me, I didn't really see a Issue Template, so I hope everything is fine :)

**Comment by TrimVis** [comment]
Moved the issue to the correct repo: https://github.com/Frewacom/pywalfox-native/issues/5
