### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by arbaes** [Frewacom/pywalfox#128]
Hello, since Python 3.12 is now the default python version on Arch-based distribution, pywalfox stopped working:

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pywalfox", line 33, in <module>
    sys.exit(load_entry_point('pywalfox==2.7.4', 'console_scripts', 'pywalfox')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/pywalfox", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 862, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pywalfox
```

Could it be possible to support it ?

**Comment by TrimVis** [comment]
I also had the same issue, telling your AUR package manager to rebuilding the package seems to resolve this error :)

E.g. I ran `paru -S --rebuild python-pywalfox`

For reference:
https://github.com/Frewacom/pywalfox-native/issues/5#issuecomment-2095775021

**Comment by uwidev** [comment]
Arch updated to 3.13. As @TrimVis has stated, rebuild the package and you are good to go.

**Comment by qukxi** [comment]
@TrimVis youre genius,thanks bro
