### ISSUE TITLE
Can't connect to pywalfox demeon

### ISSUE THREAD

**Issue by matteo-dirollo** [Frewacom/pywalfox#133]
This is the error I get when I run `pywalfox start` in the terminal:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Matteo Di Rollo\AppData\Local\Programs\Python\Python312\Scripts\pywalfox.exe\__main__.py", line 7, in <module>
  File "C:\Users\Matteo Di Rollo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pywalfox\__main__.py", line 148, in main
    handle_args(args)
  File "C:\Users\Matteo Di Rollo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pywalfox\__main__.py", line 125, in handle_args
    setup_logging(args.verbose, args.print_mode)
  File "C:\Users\Matteo Di Rollo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pywalfox\utils\logger.py", line 43, in setup_logging
    create_rotating_log('', logging.ERROR) # use the root logger
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matteo Di Rollo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pywalfox\utils\logger.py", line 16, in create_rotating_log
    handler = RotatingFileHandler(LOG_FILE_PATH, maxBytes=LOG_FILE_MAX_SIZE, backupCount=LOG_FILE_COUNT)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matteo Di Rollo\AppData\Local\Programs\Python\Python312\Lib\logging\handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "C:\Users\Matteo Di Rollo\AppData\Local\Programs\Python\Python312\Lib\logging\handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "C:\Users\Matteo Di Rollo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1231, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "C:\Users\Matteo Di Rollo\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1263, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Matteo Di Rollo\\.cache\\pywalfox.log'
```

**Comment by johanengstrand** [comment]
I believe this should be fixed in the latest version, and I verified on Windows 11 that the installation works. Sorry for taking time with this. Closing for now.
