### ISSUE TITLE
The Pywalfox extension could not create a connection to the native messenger.

### ISSUE THREAD

**Issue by YamaiKaguya** [Frewacom/Pywalfox#139]
Why am I getting this?

The Pywalfox extension could not create a connection to the native messenger. This might happen if the native messenger is outdated or if it is not installed correctly. Because of this, the extension will not work as expected.

The following error occured when trying to connect to the native messenger:
None

**Comment by ri5u** [comment]
I tried uninstalling and reinstalling. I did it both the extension and the native messaging application. 
i am still getting this error message 

The following error occured when trying to connect to the native messenger:
An unexpected error occurred

**Comment by Alan-J-Bibins** [comment]
I am also getting the same issue, trying to do `pywalfox update` on the terminal gives me an error: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 407, in from_name
    return next(iter(cls.discover(name=name)))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pywalfox", line 33, in <module>
    sys.exit(load_entry_point('pywalfox==2.7.4', 'console_scripts', 'pywalfox')())
             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/pywalfox", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 960, in distribution
    return Distribution.from_name(distribution_name)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 409, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pywalfox
```

I am not sure if the two issues are related or not.

**Comment by QubeCode** [comment]
Same problem here, I just did `pacman -Syu` and `yay -Syu`, and then it stopped working so it is probably a faulty package.

**Comment by gkursi** [comment]
same here

**Comment by Divinux** [comment]
Had the same issue, uninstalled with `pywalfox uninstall ` and reinstalled with `yay -S python-pywalfox` (on Arch, obvs).
Works for me again.

**Comment by Axenide** [comment]
I have the same issue, but uninstalling and reinstalling didn't solve it.

**Comment by Axenide** [comment]
`pywalfox uninstall` gave me the same error. Uninstalling with pacman and reinstalling solved the issue for me.

**Comment by Silver-H4ze** [comment]
just reinstall it and it will work again

**Comment by ErfanRasti** [comment]
Seems like a Python dependency was updated, causing `pywalfox` to malfunction. Try to update your packages, then reinstall `python-pywalfox`.
